---
    # OpenID Connect client registry.
    clients:
      - id: phoenix
        name: ownCloud web app
        application_type: web
        insecure: yes
        redirect_uris:
          - http://localhost:9100/oidc-callback.html
          - http://localhost:9100
          - https://localhost:9200
          - https://localhost:9200/oidc-callback.html
          - https://your-url:9200
          - https://your-url:9200/oidc-callback.html
        origins:
          - http://localhost:9100
          - https://localhost:9200
          - https://your-url:9200

      - id: owncloud10
        name: OC10
        application_type: web
        insecure: yes
        redirect_uris:
          - http://localhost:9100/oidc-callback.html
          - http://localhost:9100
          - https://localhost:9200
          - https://localhost:9200/oidc-callback.html
        origins:
          - http://localhost:9100
          - https://localhost:9200

      - id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
        secret: UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh
        name: ownCloud desktop app
        application_type: native
        insecure: true

      - id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
        secret: dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD
        name: ownCloud Android app
        application_type: native
        redirect_uris:
          - oc://android.owncloud.com

      - id: mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1
        secret: KFeFWWEZO9TkisIQzR3fo7hfiMXlOpaqP8CFuTbSHzV1TUuGECglPxpiVKJfOXIx
        name: ownCloud iOS app
        application_type: native
        redirect_uris:
          - oc://ios.owncloud.com
          - oc.ios://ios.owncloud.com
