---
    # OpenID Connect client registry.
    clients:
      - id: phoenix
        name: OCIS
        application_type: web
        insecure: yes
        redirect_uris:
          - http://localhost:9100/oidc-callback.html
          - http://localhost:9100
          - https://localhost:9200
          - https://localhost:9200/oidc-callback.html
          - https://your-url:9200
          - https://your-url:9200/oidc-callback.html
        origins:
          - http://localhost:9100
          - https://localhost:9200
          - https://your-url:9200
    
      - id: owncloud10
        name: OC10
        application_type: web
        insecure: yes
        redirect_uris:
          - http://localhost:9100/oidc-callback.html
          - http://localhost:9100
          - https://localhost:9200
          - https://localhost:9200/oidc-callback.html
        origins:
          - http://localhost:9100
          - https://localhost:9200